# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
source 'git@git.coding.net:lzbcoder/LZBSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'LZBFMWalkMan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LZBFMWalkMan
  #pod 'LZBCommonElement'
   pod 'LZBFMMain'
  
end
